### ISSUE TITLE
Ordinal::ordinal returns the *cardinal* form of a number

### ISSUE THREAD

**Issue by kamalmarhubi** [letheed/numeral#1]
The ordinal should be `first`, `second`, `third` and so on. See https://en.wikipedia.org/wiki/Ordinal_number_(linguistics)

Fun crate, though! Probably going to use it in a demo tomorrow.

**Comment by letheed** [comment]
Arff. I'm such an idiot... I meant to call it cardinal, obviously.
Thank you for reporting it.
